RabbitMQ:
  URI: amqps://tvygwybl:sAlaFyRMjc5Vn9CEz7B4mAy_mofHlxSo@cow.rmq2.cloudamqp.com/tvygwybl
Logger:
  Level: Warn
MongoDB:
  URI: mongodb+srv://root:opwswSu6uditi8ky@gopheralert.odmaj.mongodb.net/monitoring?retryWrites=true&w=majority